### PR TITLE
Use passive event listener and add support for debouncing onScroll

### PR DESCRIPTION
**Pull request by bjoerge**
This adds a couple of workarounds for the performance drops described in #45 by using passive event listeners and adding support for (optionally) debouncing the scroll event handler.

*Note*: This is strictly speaking a breaking change, since onScroll is now called with a native event instead of `React.UIEvent<HTMLDivElement>` as second parameter.

*Note 2*: Had to upgrade TypeScript to get typings for third parameter to `addEventListener`

*Note 3*: This adds the `debounce` package as dependency, so it's technically not _zero_ dependency anymore (debounce is ~500b minified & gzipped, btw.)

### CODE REVIEW

**Comment by clauderic** [comment]
Hey @bjoerge,

Thanks for submitting this PR. 

I like the idea of using passive event listeners, but in my experience I haven't really seen any performance benefits from using them in the context of virtualization. Have you documented some performance improvements from using them with `react-tiny-virtual-list` (without debouncing)?

**Comment by clauderic** [comment]
Also, if you could narrow down the scope of this PR to just passive event listeners, it would be easier for me to consider merging this.

You can split your debounce proposal into a separate PR.

**Comment by alex996** [comment]
@clauderic Any plans to get this merged?

**Comment by chadacious** [comment]
First of all, excellent work on the react-tiny-virtual-list component overall!
However, regarding this PR that appears to have died, IMHO there is definitely value to debouncing the scroll event. In my use case I have a complicated list item renderer and other unrelated animations based on events occurring in the DOM. Firing renderItem on **every** scroll event clogs up the event loop and creates a lot of jank for my user experience. The scrollbar is choppy when trying to scroll quickly, and the items jump and shift as they render and also causes other DOM events to be sluggish. With @bjoerge 's debounce PR, the scrolling is smooth and the event loop is kept clear so other DOM events can keep firing smoothly. In my case, even just adding a debounce of 25ms is enough to improve the over perception of smoothness. Would love it if this this PR was resuscitated and merged. Thanks for considering.

**Pull request closed without merging**
