### PR TITLE
Allow user to render their own wrapper (useful for tables)

### PR DESCRIPTION
**Pull request by eyn**
Thanks for the great library! I've added a renderWrapper function this allows a user to use components other the `<div>` for the two wrappers (such as `table` and `tbody` with appropriate styling). 

An example using material-ui:

```javascript
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { Table, TableHead, TableBody, TableCell, TableRow } from 'material-ui';
import { withStyles } from 'material-ui/styles';

import VirtualList from '../../src/';
import './demo.css';

const styles = ({
  table: {
    display: 'block',
    '& thead': {
      display: 'block',
    },
    '& tbody': {
      display: 'block',
    },
    '& tr': {
      display: 'table',
      width: '100%',
    },
  },
});

const TableWithRef = withStyles<any>(styles)(
  ({ classes, className, tableRef, children, ...others }: any) =>
    <table className={`${classes.table} ${className}`} ref={tableRef} {...others}>
      {children}
    </table>);

class Demo extends React.Component {
  renderWrapper = (outerProps, ref, innerStyle, items) => {
    return (
      <Table tableRef={ref} {...outerProps} component={TableWithRef}>
        <TableHead>
          <TableRow>
            <TableCell>Test</TableCell>
          </TableRow>
        </TableHead>
        <TableBody style={innerStyle}>
          {items}
        </TableBody>
      </Table>);
  }

  renderItem = ({ style, index }: { style: React.CSSProperties, index: number }) => {
    return (
      <TableRow className="Row" style={style} key={index}>
        <TableCell>
          Row #{index}
        </TableCell>
      </TableRow>
    );
  }

  render() {
    return (
      <div className="Root">
        <VirtualList
          width="auto"
          height={400}
          itemCount={1000}
          renderItem={this.renderItem}
          renderWrapper={this.renderWrapper}
          itemSize={58}
          className="VirtualList"
        />
      </div>
    );
  }
}

ReactDOM.render(<Demo />, document.querySelector('#app'));
```

### CODE REVIEW

**Comment by eyn** [comment]
Hi @clauderic - any chance of getting some feedback/getting this merged? Thanks for the awesome library :)

**Comment by thorjarhun** [comment]
Hi @eyn. I really like the functionality added in this PR! Thank you so much for sharing!

I'd like to use the wrapper from your example using material-ui but I'm using the material-ui v1 which [doesn't have support](https://github.com/mui-org/material-ui/issues/6625) for the old [fixedHeader](https://github.com/mui-org/material-ui/blob/master/src/Table/Table.js#L59) prop. I'm also using the [scrollToTransition](https://github.com/clauderic/react-tiny-virtual-list/pull/28) proposal (open at time of writing) but found that I needed to modify the `getOffsetForIndex` method to add the height of the header to the value returned. I would love a fixed header and I think some solutions to achieve that will resolve my problem with `getOffsetForIndex`. I've done some research and it appears that there are many solutions for achieving a fixed-header table but I haven't yet found one that works. By chance, are you using a material-ui table with a fixed header or have advice on what I should try to achieve it? Perhaps we could even add your example as a suggestion for using `renderWrapper` in the docs, assuming this PR goes through!

**Comment by eyn** [comment]
Hi @thorjarhun

Glad you found the PR useful! I've also struggled with getting a fixed header and a better solution is on my to-do list. At the moment I've gone down the route of using two tables - one for the header and one for the body with fixed column % widths as I know the length of most of the data I'm displaying. 

Would that work for you?

**Comment by thorjarhun** [comment]
That would be fantastic! Is the code hosted somewhere for reference? I couldn't find anything that looks like a to-do list in your repo's.

**Comment by eyn** [comment]
Ahh I don't have any public code for that - I've just copied the bit out of the relevant file below:

```js
          <div className={classes.tableContainer}>
            <Table className={classes.headerTable}>
              <TableHead>
                <TableRow>
                  <TableCell
                    className={classes.checkboxCell}
                    padding="checkbox"
                  >
                    <Checkbox
                      indeterminate={
                        select.selectedRowCount > 0 &&
                        select.selectedRowCount < rows.length
                      }
                      checked={select.selectedRowCount === rows.length}
                      onClick={this.handleSelectAllClick}
                    />
                  </TableCell>
                  {columns.map(col => (
                    <TableHeaderCell
                      key={col.name}
                      col={col}
                      sort={sort}
                      showFilter={showFilterList || col.filter.isFiltered}
                    />
                  ))}
                  <TableCell padding="none" className={classes.cellToolbar} />
                </TableRow>
              </TableHead>
            </Table>
            <VirtualList
              width="auto"
              height={height}
              itemCount={rows.length}
              renderItem={this.renderItem}
              renderWrapper={this.renderWrapper}
              tableState={tableState}
              itemSize={48}
              overscanCount={20}
              className={classes.bodyTable}
              rows={rows}
            />
          </div>
```

Hopefully that will get you pointed in the right direction

**Comment by mihiramin89** [comment]
Any updates on when this will be merged? I am using a table that can really use this for the body.

**Comment by prescottprue** [comment]
I agree this would be useful. Any input on when it is getting merged?

**Comment by VALIKCOOL** [comment]
Hi. Very useful PR that would be awesome to see merged into this library. Will it be merged?

**Comment by towfiqi** [comment]
+1 Kindly merge this..

**Comment by atrauzzi** [comment]
Yikes, what's the holdup here?

**Comment by baronmog** [comment]
Is this going anywhere? I'm working on a project that already uses react-tiny-virtual-list. We're in the process of integrating material-ui into it and would like to continue using react-tiny-virtual-list, but...

**Comment by eyn** [comment]
I've tried contacting @clauderic via other channels but no success so doesn't look like it 😢 I have been using this patch in production for quite a while so it does work..

**Comment by clauderic** [comment]
This PR has merge conflicts and I'm not 100% satisfied with the approach, the function signature for the `renderWrapper` is too complex in my opinion.

I'm going to close this PR for the moment as I don't have any intention of merging it in it's current state, but we can keep the discussion open. 

To be clear, I agree that this is an important use case and I am willing to support it, but I'd rather spend a bit more time to make the API more elegant.

**Pull request closed without merging**
